language: php
php:
  - 5.6

before_script:
  - composer install

script:
  - phpunit --bootstrap test/config.php --coverage-clover=coverage.clover test

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover